[Draft] Scoring monasteries
YetAnotherSpieskowcy/Carcassonne-Engine pull request #33
Opened 2024-04-15 21:35 UTC by Lenetis

2024-04-22 09:15 UTC, BognaLew approved these changes

2024-07-04 19:15 UTC, BognaLew approved these changes

2024-07-05 13:04 UTC, Kaszana102 requested changes

2024-07-05 14:16 UTC, Lenetis commented on pkg/game/elements/score_report.go
> +func (report *ScoreReport) Update(otherReport ScoreReport) {
Yeah, you're right about that, update is not the correct word. However, I don't like the repetition in `report.JoinReport`. What do you think about just `Join`? Or maybe `Combine` or `Merge`?

2024-07-06 10:29 UTC, BognaLew approved these changes

2024-07-06 19:43 UTC, Kaszana102 approved these changes

2024-07-07 10:53 UTC, merged