Scoring cities
YetAnotherSpieskowcy/Carcassonne-Engine pull request #40
Opened 2024-07-02 15:28 UTC by BognaLew

Closes #19

2024-07-05 10:10 UTC, bstrzelecki submitted a review, later dismissed

2024-07-05 10:10 UTC, bstrzelecki commented on pkg/game/city/city.go
> +// Returnes all features from a tile at a given position that are part of a city
```suggestion
// Returns all features from a tile at a given position that are part of a city
```

2024-07-05 10:10 UTC, bstrzelecki commented on pkg/game/city/city.go
> +// Merges two cities when they are connetced.
```suggestion
// Merges two cities when they are connected.
```

2024-07-05 10:10 UTC, bstrzelecki commented on pkg/game/city/city_manager.go
> +// Performes required operations to add a new city feature.
```suggestion
// Performs required operations to add a new city feature.
```

2024-07-05 10:10 UTC, bstrzelecki commented on pkg/game/city/city.go
> +func (city City) GetCompleted() bool {
Maybe IsCompleted?

2024-07-05 10:10 UTC, bstrzelecki commented on pkg/game/city/city.go
> +					case side.Top:
Using [PositionFromSide](https://github.com/YetAnotherSpieskowcy/Carcassonne-Engine/blob/f9fd846edf803179db7d10676847d1395887284c/pkg/game/elements/placed_tile.go#L39) would by slightly cleaner.

2024-07-05 12:58 UTC, bstrzelecki submitted a review, later dismissed

2024-07-05 16:11 UTC, Lenetis requested changes

2024-07-05 16:11 UTC, Lenetis commented on pkg/game/city/city_manager_test.go
> +	}
This should probably check all positions instead of just top

2024-07-05 16:12 UTC, Lenetis commented
Also, consider adding a test for this kind of city setup:
![image](https://github.com/YetAnotherSpieskowcy/Carcassonne-Engine/assets/70149832/4dce94ac-9f3c-45c5-a24a-cad67e3d488b)

2024-07-08 12:09 UTC, Lenetis approved these changes

2024-07-08 12:09 UTC, Lenetis commented on pkg/game/city/city_manager.go
> +				// I guess panic
Yup, I think panic would be alright here

2024-07-08 12:09 UTC, Lenetis commented on pkg/game/city/city_manager.go
> +					println("aaa")
Probably to remove :)

2024-07-08 12:09 UTC, Lenetis commented on pkg/game/city/city_manager.go
> +// closed cities and sets city.score to true. Otherwise calculates score based on
```suggestion
// closed cities and sets city.scored to true. Otherwise calculates score based on
```

2024-07-08 18:51 UTC, bstrzelecki approved these changes

2024-07-08 18:54 UTC, merged